// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrder struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type Order struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}
